apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
        app: postgres-pod
        type: demo-voting-app
  template:
    metadata:
      name: postgres-pod
      labels:
        app: postgres-pod
        type: demo-voting-app
    spec:
      containers:
        - name: postgres-app
          image: postgres:9.4
          ports:
          - containerPort: 5432
          env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"