apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
        app: result-pod
        type: demo-voting-app
  template:
    metadata:
      name: result-pod
      labels:
        app: result-pod
        type: demo-voting-app
    spec:
      containers:
        - name: result-app
          image: dockersamples/examplevotingapp_result
          ports:
          - containerPort: 80