
#REDIS SERVICE

apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis-pod
    type: demo-voting-app
  ports:
  - port: 6379
    targetPort: 6379 
---
 #db SERVICE
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: postgres-pod
    type: demo-voting-app
  ports:
  - port: 5432
    targetPort: 5432 

---
#VOTING APP SERVICE
apiVersion: v1
kind: Service
metadata:
  name: voting-app
spec:
  type: NodePort
  selector:
    app: voting-pod
    type: demo-voting-app
  ports:
  - port: 80
    targetPort: 80
    
---
#Result app
apiVersion: v1
kind: Service
metadata:
  name: result-app
spec:
  type: NodePort
  selector:
    app: result-pod
    type: demo-voting-app
  ports:
  - port: 80
    targetPort: 80

